In [2]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.ndim

1

In [13]:
arr1.size

4

In [17]:
arr1.shape

(4,)

In [14]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
arr2.ndim

2

In [16]:
arr2.size

8

In [18]:
arr2.shape

(2, 4)

In [19]:
arr2.dtype

dtype('int32')

# lec 2

In [20]:
import numpy as np

In [25]:
ls=[[1,1,1],[1,1,1],[1,1,1]]

In [26]:
print(ls)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]


In [29]:
ls=np.ones(5)

In [30]:
ls.dtype

dtype('float64')

In [32]:
ls=np.ones((3,4))
ls

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
ls=np.ones((3,4),dtype=int)
ls

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
ls=np.zeros((3,4),dtype=int)
ls

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
ls=np.zeros((3,4),dtype=bool)
ls

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
ls=np.zeros((3,4),dtype=str)
ls

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [40]:
ls=np.empty((3,3))
print(ls)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.46237865e-321]
 [8.34420522e-308 1.44635488e-307 1.37962320e-306]]


In [41]:
import numpy as np

# arange

In [52]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
arr=np.arange(1,13,2)
arr

array([ 1,  3,  5,  7,  9, 11])

# linspace

In [46]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [54]:
arr2=arr.reshape(2,6)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [56]:
arr3=arr.reshape(2,3,2)
print(arr3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [57]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [58]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [59]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [60]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# lect 3

In [61]:
import numpy as np

In [65]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [67]:
arr1+arr2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [68]:
arr1-arr2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [69]:
arr1/arr2

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [70]:
arr1*arr2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [71]:
np.add(arr1,arr2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [73]:
np.subtract(arr1,arr2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [74]:
np.divide(arr1,arr2)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [75]:
np.multiply(arr1,arr2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [76]:
arr1@arr2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [77]:
np.dot(arr1,arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [78]:
arr1.min()

1

In [79]:
arr1.max()

9

In [80]:
arr1.argmax()

8

In [81]:
arr1.max(axis = 0)

array([7, 8, 9])

In [82]:
arr1.max(axis = 1)

array([3, 6, 9])

In [84]:
np.sum(arr1)

45

In [85]:
np.sum(arr2)

135

In [86]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [87]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [88]:
np.mean(arr1)

5.0

In [89]:
np.mean(arr2)

15.0

In [90]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [91]:
np.std(arr1)

2.581988897471611

In [92]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# slicing

In [8]:
import numpy as np

In [9]:
arr1=np.arange(1,101).reshape(10,10)
print(arr1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [10]:
arr1[0,0]

1

In [11]:
len(arr1)

10

In [12]:
arr1.ndim

2

In [13]:
arr1.shape

(10, 10)

In [15]:
arr1[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [16]:
arr1[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [17]:
arr1[:,0:1].ndim

2

In [19]:
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
arr1[1:4,2:6]

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

In [22]:
arr1[:,1:5]

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55],
       [62, 63, 64, 65],
       [72, 73, 74, 75],
       [82, 83, 84, 85],
       [92, 93, 94, 95]])

In [23]:
arr1[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [24]:
arr1[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [25]:
arr1[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [26]:
arr1.itemsize

4

In [27]:
arr1.dtype

dtype('int32')

# conctination and split

In [28]:
import numpy as np

In [30]:
arr1=np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
arr2=np.arange(17,33).reshape(4,4)
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [35]:
list1=[2,4,6,7]
list2=[1,8,3,5]

In [36]:
list1 + list2

[2, 4, 6, 7, 1, 8, 3, 5]

In [37]:
arr1 + arr2 

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [39]:
arr3= np.concatenate((arr1,arr2))
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [40]:
arr3.ndim

2

In [41]:
arr3.shape

(8, 4)

In [42]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [43]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [44]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [45]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [47]:
list1=np.split(arr1,2)
list1

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [48]:
type(list1)

list

In [49]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
type(list1[0])

numpy.ndarray

# sin() , cos() , tan()

In [53]:
import numpy as np
import matplotlib.pyplot as plt

In [54]:
np.sin(90)

0.8939966636005579

In [55]:
np.cos(90)

-0.4480736161291701

# random sampling with numpy

In [64]:
import numpy as np
import random

In [65]:
np.random.random(1)

array([0.31402691])

In [66]:
np.random.random((3,3))

array([[0.61571238, 0.39287166, 0.82457253],
       [0.8605401 , 0.70120252, 0.74539405],
       [0.45969382, 0.45544028, 0.60197499]])

In [71]:
l1=np.random.randint(1,8,(4,4))
l1

array([[2, 2, 1, 7],
       [5, 1, 5, 2],
       [7, 5, 4, 4],
       [5, 4, 2, 5]])